#!/usr/bin/env python3

from src.main import *
from lib.banner import banner
from datetime import datetime
from lib.colors import red, white, green, reset

print(banner)
if __name__ == "__main__":
    while True:
    	try:
    		oxdork(args)
    		break
    		
    	except KeyboardInterrupt:
    		if args.verbose:
    			print("\n")
    			logging.warning(f"{white}Process interrupted with {red}Ctrl{white}+{red}C{reset}")
    			break
    		break
    		
    	except Exception as e:
    		if args.verbose:
    			logging.warning(f"{white}Error: {red}{e}{reset}")
    			
    if args.verbose:
    	logging.info(f"{white}Stopped in {green}{datetime.now()-start_time}{white} seconds.{reset}")
