#!/usr/bin/env python3

from core.__main__ import *
from assets.colors import red, white, green, end

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description=f"{red}0x{white}Dork{red}: Google dorking tool developed by {white}rly0nheart{red}. https://github.com/rlyonheart{end}")
	parser.add_argument("query", help="search query")
	parser.add_argument("-c","--count",help="number of results to show",dest="count", metavar="RESULTS COUNT", default=50)
	parser.add_argument("-o","--outfile",help="output filename",dest="output", metavar="OUTPUT FILENAME")
	args = parser.parse_args()

	logging.info(f"{white}Fetching [{red}{args.count}{end}{white}] dorks [{green}{args.query}{white}]...{end}")
	Dork().on_connect(args)
			
		
